# Generated by Django 5.2.3 on 2025-06-14 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='design/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('about', 'About'), ('contact', 'Contact')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=50)),
                ('about_us_body', models.CharField(max_length=500)),
                ('contact_num', models.CharField(max_length=20)),
                ('contact_mail', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ImageInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_design.designimage')),
                ('image_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_design.imagelist')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('image_list', 'position')},
            },
        ),
    ]
